# Generated by Django 5.2.8 on 2025-12-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropink', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('review', models.TextField()),
            ],
        ),
    ]
