# Generated by Django 5.2.8 on 2025-12-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropink', '0003_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
