# Generated by Django 5.2.8 on 2025-12-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropink', '0004_alter_testimonials_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
