# Generated by Django 5.2.8 on 2025-12-02 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropink', '0005_testimonials_approved_testimonials_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
