# Generated by Django 5.2.8 on 2025-12-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropink', '0006_testimonials_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
