# Generated by Django 5.2.8 on 2025-12-25 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropink', '0007_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='access_token',
            field=models.UUIDField(null=True, editable=False),
        ),
    ]
