# Generated by Django 5.2.8 on 2025-12-25 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropink', '0009_populate_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
