# Generated by Django 5.2.8 on 2025-12-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropink', '0010_alter_order_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_order_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
