# Generated by Django 5.2.8 on 2025-12-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuropink', '0011_order_completed_order_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='poslato',
            field=models.BooleanField(default=False),
        ),
    ]
